const {chromium,expect} = require('@playwright/test');
const mysql = require('mysql2/promise');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const {spawn} = require('node:child_process');
const crypto = require('node:crypto');
require('dotenv').config({quiet:true});

(async()=>{
    fs.mkdirSync('artifacts',{recursive:true});
    const dbName='clinica_ui_test_'+Date.now();
    const temp=fs.mkdtempSync(path.join(os.tmpdir(),'clinica-ui-'));
    const db=await mysql.createConnection({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,multipleStatements:true});
    let child,browser;
    const errors=[],checks=[];
    const record=checks.push.bind(checks);
    checks.push=(message)=>{console.log('OK:',message);return record(message);};
    try {
        await db.query('CREATE DATABASE ??',[dbName]); await db.changeUser({database:dbName});
        await db.query(fs.readFileSync('database/clinica.sql','utf8'));
        await db.query(fs.readFileSync('database/datos-iniciales.sql','utf8'));
        const password=crypto.randomBytes(18).toString('hex');
        for(const [id,name,rut,role,critical] of [[1,'Soporte QA','11111111-1',1,0],[2,'Funcionario QA','22222222-2',2,0],[3,'Critico QA','33333333-3',2,1]]) {
            await db.query("INSERT INTO user (user_id,first_name,first_last_name,second_last_name,institutional_email,rut,username,password_hash,is_critical_tech) VALUES (?,?,'','',?,?,?,?,?)",[id,name,`${id}@temp.com`,rut,rut,password,critical]);
            await db.query('INSERT INTO user_role (assignment_date,active,role_id,user_id) VALUES (NOW(),1,?,?)',[role,id]);
        }
        for(const file of ['index.html','css','js','vendor']) fs.cpSync(path.join('public',file),path.join(temp,file),{recursive:true});
        fs.mkdirSync(path.join(temp,'uploads'));fs.mkdirSync(path.join(temp,'manuales'));
        child=spawn(process.execPath,['scripts/test-server.cjs'],{env:{...process.env,NODE_ENV:'test',CLINICA_DATA_DIR:'',CLINIC_TEST_PORT:'3200',DB_NAME:dbName,CLINIC_TEST_PUBLIC:temp,IMER_WEBHOOK_TOKEN:'acceptance-isolated'},stdio:['ignore','pipe','pipe'],windowsHide:true});
        let serverLog='';child.stdout.on('data',d=>serverLog+=d);child.stderr.on('data',d=>serverLog+=d);
        let ready=false;
        for(let i=0;i<120;i++){if(child.exitCode!==null)break;try{if((await fetch('http://127.0.0.1:3200')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}
        if(!ready)throw Error('Servidor QA no disponible: '+serverLog);
        browser=await chromium.launch();
        const context=await browser.newContext({viewport:{width:1440,height:1000}});
        const page=await context.newPage();
        page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.stack);});
        page.on('response',r=>{if(r.status()>=500 || r.status()===401 || r.status()===403)errors.push(`${r.status()} ${new URL(r.url()).pathname}`);});
        page.on('console',m=>{if(m.type()==='error' && !m.text().includes('net::ERR_FAILED'))errors.push(m.text());});
        const login=async(rut)=>{
            await context.setExtraHTTPHeaders({});
            await page.goto('http://127.0.0.1:3200');
            await page.locator('.welcome-panel').getByRole('button',{name:'Iniciar sesión'}).click();
            await page.locator('[x-model="login.rut"]').fill(rut);
            await page.locator('[x-model="login.pass"]').fill(password);
            await page.locator('[x-show="authTab===\'login\'"]').getByRole('button',{name:/Ingresar|Iniciar/i}).click();
            await expect(page.locator('.page-heading h1')).toBeVisible();
            await context.setExtraHTTPHeaders({Authorization:'Bearer '+await page.evaluate(()=>Alpine.$data(document.documentElement).usuario.token)});
            await page.evaluate(()=>Alpine.$data(document.documentElement).cargarActivosBackground());
        };
        await login('22222222-2');
        await expect(page.locator('.side-links').getByRole('button',{name:'Administración',exact:true})).toBeHidden();
        await expect(page.locator('.page-heading h1')).toHaveText('Mis tickets');
        checks.push('Login funcionario y permisos de navegación');
        await page.locator('.page-heading').getByRole('button',{name:'Nuevo incidente'}).click();
        const form=page.locator('[x-show="modalIncidente"]');
        await form.getByRole('button',{name:'Generar Ticket',exact:true}).click();
        await expect(form.locator('.msg')).not.toBeEmpty();
        await form.locator('[x-model="inc.piso"]').selectOption({label:'Piso 1'});
        await form.locator('[x-model="inc.habitacion"]').selectOption({label:'Recepción'});
        await form.locator('[x-model="inc.aparato"]').selectOption({label:'Computador/Hardware'});
        await form.locator('[x-model="inc.nombreActivo"]').fill('Equipo de prueba aislada');
        await form.locator('[x-model="inc.priority_id"]').selectOption('1');
        await form.locator('[x-model="inc.descripcion"]').fill('Comprobación funcional de creación en base temporal.');
        const created=page.waitForResponse(r=>r.url().endsWith('/incidente') && r.request().method()==='POST');
        await form.getByRole('button',{name:'Generar Ticket',exact:true}).click();
        expect((await created).status()).toBe(200);
        await expect(form).toBeHidden({timeout:10000});
        await expect(page.locator('.ticket-link')).toHaveCount(1);
        const code=await page.locator('.ticket-link').textContent();
        checks.push('Validación, creación y actualización automática de Mis tickets');
        await page.locator('.ticket-link').click();
        await expect(page.locator('.detail-window')).toBeVisible({timeout:15000});
        await expect(page.locator('.ticket-info-block')).toContainText('Comprobación funcional');
        await expect(page.locator('.detail-window').getByRole('button',{name:'Resolver',exact:true})).toBeHidden();
        await page.locator('.win-ctrl.close').click();
        await page.getByRole('textbox',{name:'Buscar ticket por ID o palabra clave'}).fill(code);
        await expect(page.locator('.page-heading h1')).toHaveText('Resultados de búsqueda');
        await expect(page.locator('.loading-state')).toBeHidden();
        await expect(page.locator('.ticket-link')).toHaveText(code);
        await page.locator('[x-model="filtroEstado"]').selectOption('Resuelto');
        await expect(page.getByText('Sin coincidencias con estos filtros',{exact:true})).toBeVisible();
        await page.locator('.empty-state').getByRole('button',{name:'Limpiar filtros',exact:true}).click();
        await expect(page.locator('.ticket-link')).toBeVisible();
        checks.push('Consulta, búsqueda y filtros');
        await page.locator('.side-links').getByRole('button',{name:'Historial',exact:true}).click();
        await expect(page.getByText('Aún no hay tickets cerrados',{exact:true})).toBeVisible();
        await page.getByRole('button',{name:'Volver a tickets activos'}).click();
        await expect(page.locator('.ticket-link')).toBeVisible();
        await page.locator('.side-links').getByRole('button',{name:'Manuales de equipos',exact:true}).click();
        await expect(page.locator('[x-show="modalManuales"]')).toBeVisible();
        await expect(page.locator('[x-show="modalManuales"] input[type="file"]')).toBeHidden();
        await page.locator('[x-show="modalManuales"] .close-btn').click();
        checks.push('Historial vacío, retorno a activos y manuales según permisos');
        await page.evaluate(()=>{localStorage.clear();});
        await login('11111111-1');
        await expect(page.locator('.page-heading h1')).toHaveText('Bandeja de soporte');
        await page.getByRole('button',{name:'Mis asignados',exact:true}).click();
        await expect(page.locator('.ticket-link')).toHaveCount(1);
        await page.getByRole('button',{name:'Sin asignar',exact:true}).click();
        await expect(page.locator('.ticket-link:visible')).toHaveCount(0);
        await page.locator('.quick-filters').getByRole('button',{name:'Todos',exact:true}).click();
        await expect(page.locator('.ticket-link')).toBeVisible();
        checks.push('Filtros rápidos de soporte');
        await page.locator('.ticket-link').click();
        await expect(page.locator('.detail-window')).toBeVisible();
        await expect(page.locator('.detail-window .badge-estado')).toHaveText('En curso');
        fs.mkdirSync('artifacts',{recursive:true});
        await page.screenshot({path:'artifacts/prueba-detalle.png',fullPage:true});
        await page.locator('.win-ctrl[title="Minimizar"]').click();
        await expect(page.locator('.detail-window')).toHaveClass(/minimized/);
        await page.locator('.win-ctrl[title="Minimizar"]').click();
        await page.locator('.win-ctrl[title="Maximizar"]').click();
        await expect(page.locator('.detail-window')).toHaveClass(/maximized/);
        await page.locator('.win-ctrl[title="Maximizar"]').click();
        await page.locator('.win-ctrl.close').click();
        await page.locator('.side-links').getByRole('button',{name:'Administración',exact:true}).click();
        await expect(page.locator('.admin-panel-card')).toHaveCount(29);
        const names=await page.locator('.admin-panel-card').evaluateAll(buttons=>buttons.filter(b=>{const a=b.getAttribute('@click')||'';return !a.startsWith('v3OpenSection')&&!a.includes('modalUsuariosCSV')&&!a.includes('respaldoManual');}).map(b=>b.querySelector('.label').textContent));
        for(const name of names){
            await page.locator('.admin-panel-card').filter({has:page.locator('.label',{hasText:name})}).click();
            const dialog=page.locator('.modal-overlay:visible,.stats-overlay:visible');
            await expect(dialog).toHaveCount(1);
            await page.waitForTimeout(180);
            const close=dialog.locator('.close-btn, .stats-header button').first();
            await close.click();
            await page.locator('.side-links').getByRole('button',{name:'Administración',exact:true}).click();
        }
        checks.push('15 herramientas administrativas abren y cierran');
        await page.locator('.side-links').getByRole('button',{name:'Manuales de equipos',exact:true}).click();
        const manual=page.locator('[x-show="modalManuales"]');
        const PDFDocument=require('pdfkit');
        const pdf=path.join(temp,'qa.pdf');
        await new Promise(resolve=>{const out=fs.createWriteStream(pdf);const doc=new PDFDocument();doc.pipe(out);doc.text('Manual de prueba aislada');doc.end();out.on('finish',resolve);});
        await manual.locator('input[type="file"]').setInputFiles(pdf);
        await expect(manual.locator('.manual-item')).toHaveCount(1,{timeout:10000});
        const url=await manual.locator('.manual-item a').first().getAttribute('href');
        expect((await page.request.get(new URL(url,page.url()).href)).status()).toBe(200);
        await manual.locator('.close-btn').click();
        checks.push('Carga y consulta de manual PDF en carpeta temporal');
        await db.query('UPDATE ticket SET status_id=4,resolution_date=NOW() WHERE ticket_code=?',[code]);
        await page.locator('.side-links').getByRole('button',{name:'Historial',exact:true}).click();
        await expect(page.locator('.ticket-link')).toHaveText(code);
        checks.push('Historial con ticket resuelto real en base temporal');
        await page.route('**/incidentes?*',r=>r.abort());
        await page.locator('.side-links').getByRole('button',{name:'Bandeja de soporte',exact:true}).click();
        await expect(page.locator('.error-state')).toBeVisible();
        await page.unroute('**/incidentes?*');
        await page.locator('.error-state').getByRole('button',{name:'Reintentar'}).click();
        await expect(page.locator('.error-state')).toBeHidden();
        checks.push('Error de conexión y reintento');
        await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(250);
        expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
        await page.getByRole('button',{name:'Abrir navegación',exact:true}).click();
        await page.locator('.side-links').getByRole('button',{name:'Historial',exact:true}).click();
        await expect(page.locator('.sidebar')).not.toHaveClass(/is-open/);
        await page.locator('.ticket-link').click();
        await expect(page.locator('.detail-window')).toBeVisible();
        const bounds=await page.locator('.detail-window').boundingBox();
        expect(bounds.x>=0 && bounds.width<=390).toBe(true);
        await page.locator('.win-ctrl.close').click();
        checks.push('Navegación móvil y detalle sin desbordamiento');
        for(const name of names){
            await page.getByRole('button',{name:'Abrir navegación',exact:true}).click();
            await page.locator('.side-links').getByRole('button',{name:'Administración',exact:true}).click();
            await page.locator('.admin-panel-card').filter({has:page.locator('.label',{hasText:name})}).click();
            const dialog=page.locator('.modal-overlay:visible,.stats-overlay:visible');
            await expect(dialog).toHaveCount(1);
            const box=await dialog.locator('.modal-box,.stats-box').boundingBox();
            expect(box.x>=0 && box.x+box.width<=391).toBe(true);
            await dialog.locator('.close-btn,.stats-header button').first().click();
        }
        checks.push('15 herramientas administrativas comprobadas a 390 px');
        await page.setViewportSize({width:1440,height:1000});
        await page.evaluate(()=>localStorage.clear());
        await login('33333333-3');
        await expect(page.locator('.side-links').getByRole('button',{name:'Administración',exact:true})).toBeHidden();
        await expect(page.getByRole('button',{name:'Stock de repuestos',exact:true}).first()).toBeVisible();
        checks.push('Rol técnico crítico conserva accesos específicos');
        const catalog=['Computador/Hardware','Impresora','Teléfono IP','Sistema/Software','Red/Internet','Sistema Externo (ej. IMER)'];
        for(const [index,aparato] of catalog.entries()) {
            const response=await page.request.post('http://127.0.0.1:3200/incidente',{data:{creador:'Funcionario QA',piso:'Piso 1',habitacion:'Recepción',aparato,descripcion:'Verificación de persistencia para cada categoría.',category_id:index+1,priority_id:1,nombreActivo:[0,4].includes(index)?'Activo QA '+index:''}});
            expect(response.status()).toBe(200);
        }
        const [persisted]=await db.query("SELECT COUNT(DISTINCT category_id) total FROM ticket WHERE description='Verificación de persistencia para cada categoría.'");
        expect(persisted[0].total).toBe(6);
        checks.push('Creación y persistencia MySQL en las seis categorías, con y sin activo');
        expect(errors).toEqual([]);
        await require('./production-acceptance-checks.cjs')({db,page,login});
        await require('./production-audit-downloads.cjs')({db,page,login});
        await require('./production-audit-admin.cjs')({db,page});
        const expectedHttpErrors=errors.filter(e=>e==='Failed to load resource: the server responded with a status of 400 (Bad Request)');
        const unexpectedErrors=errors.filter(e=>!expectedHttpErrors.includes(e));
        expect(unexpectedErrors).toEqual([]);
        fs.writeFileSync('artifacts/verificacion.json',JSON.stringify({checks,pageErrors:unexpectedErrors,expectedHttpErrors,isolatedDatabase:true},null,2));
        console.log(checks.join('\n')); console.log('Errores inesperados:',unexpectedErrors.length);
    } finally {
        if(browser)await browser.close();
        if(child && child.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}
        await db.changeUser({database:'mysql'});
        await db.query('DROP DATABASE ??',[dbName]);await db.end();
        if(path.dirname(temp)===os.tmpdir() && path.basename(temp).startsWith('clinica-ui-')) fs.rmSync(temp,{recursive:true,force:true});
    }
})().catch(e=>{console.error(e);process.exitCode=1});
