const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {Usuario,EstadoTicket,NotificacionCorreo}=require('./domain');
const multer=require('multer'),XLSX=require('xlsx'),passwords=require('./passwords');
module.exports=function register(app,{pool,uploadDir,validarRutModulo11,transporter,obtenerComentariosParaViewer,enviarEmailTicketResuelto}){
 const api={config:{upload_mb:10,manual_mb:50,cost_threshold:100000,saturation:5}};
 const fallback=path.resolve(process.env.CLINICA_LOG_FALLBACK||path.join(__dirname,'../.local-backup/technical-errors.log'));
 const logger=new (require('./technical-logger'))(pool,fallback);
 const redact=value=>logger.redact(value);
 api.log=logger.write.bind(logger);
 api.ready=require('./increment3-schema')(pool).then(async()=>{api.config=(await pool.query('SELECT * FROM inc3_config WHERE id=1'))[0][0];}).catch(async e=>{await api.log(e,'critical',{operation:'migration'});throw e;});
 api.ready.catch(()=>{});
 app.use(async(req,res,next)=>{try{await api.ready;next();}catch{res.status(503).json({error:'No se pudo preparar el incremento 3. Revisa el registro técnico.'});}});
 app.use(async(req,res,next)=>{const token=(req.headers.authorization||'').replace(/^Bearer /,'');if(!token||['/api/v3/password','/login','/sesion/cerrar','/integraciones/imer/webhook'].includes(req.path))return next();try{const [[u]]=await pool.query('SELECT must_reset_password,user_status FROM user WHERE session_token=?',[token]);if(!u||!u.user_status)return res.status(401).json({error:'Sesión inválida o cuenta deshabilitada.'});if(u.must_reset_password)return res.status(428).json({error:'Debes cambiar tu contraseña temporal.'});next();}catch(e){next(e);}});
 const wrap=fn=>async(req,res,next)=>{try{await fn(req,res,next);}catch(e){if((!e.status||e.status>=500)&&e.code!=='ER_DUP_ENTRY')await api.log(e,'error',{path:req.path});if(!res.headersSent)res.status(e.status|| (e.code==='ER_DUP_ENTRY'?409:500)).json({error:e.status?e.message:e.code==='ER_DUP_ENTRY'?'El registro ya existe.':'No se pudo completar la operación.'});}};
 const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
 const actor=wrap(async(req,res,next)=>{
  const token=(req.headers.authorization||'').replace(/^Bearer /,'');if(!token)fail('Inicia sesión para continuar.',401);
  const [rows]=await pool.query("SELECT u.*,EXISTS(SELECT 1 FROM user_role ur WHERE ur.user_id=u.user_id AND ur.role_id=1 AND ur.active=1) admin FROM user u WHERE session_token=? AND user_status=1",[token]);
  if(!rows.length)fail('Sesión inválida o cuenta deshabilitada.',401);req.actor=rows[0];req.identity=Usuario.desde(req.actor);
  if(req.actor.must_reset_password && req.path!=='/password')fail('Debes cambiar tu contraseña temporal.',428);next();
 });
 const admin=(req,res,next)=>req.identity.obtenerPermisos().admin?next():res.status(403).json({error:'Se requiere administrador.'});
 const support=(req,res,next)=>req.identity.obtenerPermisos().soporte?next():res.status(403).json({error:'Se requiere personal de soporte.'});
 const router=require('express').Router();app.use('/api/v3',actor,router);
 const audit=async(c,req,t,action,previous,value)=>c.query('INSERT INTO audit_log(action_type,affected_table,affected_record_id,previous_value,new_value,ip_address,user_id,ticket_id) VALUES (?,\'ticket\',?,?,?,?,?,?)',[action,t.ticket_id,JSON.stringify(previous),JSON.stringify(value),req.ip,req.actor.user_id,t.ticket_id]);
 const access=(req,t)=>{if(!req.identity.obtenerPermisos().soporte&&t.requester_user_id!==req.actor.user_id&&t.assigned_user_id!==req.actor.user_id)fail('No tienes acceso a este ticket.',403);};
 const ticket=async(req,c=pool,lock=false)=>{const [rows]=await c.query('SELECT * FROM ticket WHERE ticket_code=?'+(lock?' FOR UPDATE':''),[req.params.code||req.body.id_ticket]);if(!rows.length)fail('Ticket no encontrado.',404);access(req,rows[0]);return rows[0];};
 const mutable=t=>{if(t.is_archived)fail('Ticket archivado: solo lectura.',409);};
 api.assign=async(categoryId,priorityId,connection=pool)=>{
  if(connection!==pool)await connection.query("SELECT user_id FROM user WHERE user_status=1 ORDER BY user_id FOR UPDATE");
  const [r]=await connection.query(`SELECT u.user_id,u.first_name,COUNT(DISTINCT t.ticket_id) carga,MAX(cpm.preferred_user_id=u.user_id) preferido FROM user u JOIN user_role ur ON ur.user_id=u.user_id AND ur.active=1 LEFT JOIN ticket t ON t.assigned_user_id=u.user_id AND t.status_id IN(1,2,5) AND t.is_archived=0 LEFT JOIN category_priority_matrix cpm ON cpm.category_id=? AND cpm.priority_id=? WHERE (ur.role_id=1 OR u.is_critical_tech=1 OR u.tipo_usuario='TECNICO') AND u.user_status=1 AND u.en_vacaciones=0 AND (u.competencies_configured=0 OR EXISTS(SELECT 1 FROM inc3_competency c WHERE c.user_id=u.user_id AND c.category_id=?)) GROUP BY u.user_id HAVING COUNT(DISTINCT t.ticket_id)<3 ORDER BY carga ASC,preferido DESC,u.user_id LIMIT 1`,[categoryId,priorityId,categoryId]);return r[0]||null;
 };
 // Login compatible con cuentas antiguas: migra su contraseña al validar el primer acceso.
 app.post('/login',wrap(async(req,res)=>{
  const {rut,password}=req.body;if(typeof password!=='string')fail('Credenciales inválidas.',401);
  const [rows]=await pool.query('SELECT u.*,EXISTS(SELECT 1 FROM user_role ur WHERE ur.user_id=u.user_id AND ur.role_id=1 AND ur.active=1) admin FROM user u WHERE rut=? AND user_status=1',[rut]);const u=rows[0];
  if(!u||!await passwords.verify(password,u.password_hash))fail('Contraseña incorrecta o usuario no encontrado.',401);
  const token=crypto.randomBytes(32).toString('hex');await pool.query('UPDATE user SET session_token=?,last_seen=NOW(),last_login=NOW(),password_hash=? WHERE user_id=?',[token,/^\$2/.test(u.password_hash)?u.password_hash:await passwords.hash(password),u.user_id]);
  res.json({success:true,user_id:u.user_id,nombre:u.first_name,rut:u.rut,correo:u.institutional_email.includes('@temp.com')?'':u.institutional_email,permisos:u.admin?'si':'no',esCritico:!!u.is_critical_tech,esTecnico:u.tipo_usuario==='TECNICO',token,mustReset:!!u.must_reset_password});
 }));
 router.post('/password',wrap(async(req,res)=>{const {password,current}=req.body;if(typeof password!=='string'||password.length<8||Buffer.byteLength(password,'utf8')>72)fail('La contraseña debe tener al menos 8 caracteres y un máximo de 72 bytes.');if(!req.actor.must_reset_password&&!await passwords.verify(current||'',req.actor.password_hash))fail('Contraseña actual incorrecta.');await pool.query('UPDATE user SET password_hash=?,must_reset_password=0 WHERE user_id=?',[await passwords.hash(password),req.actor.user_id]);res.json({success:true});}));
 router.get('/profile',wrap(async(req,res)=>{const u=req.actor;res.json({user_id:u.user_id,nombre:u.first_name,rut:u.rut.replace(/(\d)(?=(\d{3})+-)/g,'$1.'),username:u.username,correo:u.institutional_email,area:u.operational_area||'',piso:u.operational_floor||'',cargo:u.job_title||'',rol:u.admin?'Administrador':u.is_critical_tech?'Técnico crítico':u.tipo_usuario==='TECNICO'?'Técnico':'Usuario'});}));
 router.put('/profile',wrap(async(req,res)=>{const {area,piso}=req.body;if(typeof area!=='string'||typeof piso!=='string'||!area.trim()||!piso.trim()||area.length>100||piso.length>50)fail('Indica área (máximo 100 caracteres) y piso (máximo 50).');if(Object.keys(req.body).some(k=>!['area','piso'].includes(k)))fail('RUT, nombre y usuario son inmutables.');await pool.query('UPDATE user SET operational_area=?,operational_floor=? WHERE user_id=?',[area.trim(),piso.trim(),req.actor.user_id]);res.json({success:true});}));
 app.post('/editar-perfil',actor,(req,res)=>res.status(400).json({error:'Usa Mi perfil para actualizar área/piso o cambiar tu contraseña. Nombre y RUT son inmutables.'}));
 router.get('/categories',wrap(async(req,res)=>res.json((await pool.query('SELECT * FROM category ORDER BY category_id'))[0])));
 router.put('/categories/:id',admin,wrap(async(req,res)=>{const {nombre,activo}=req.body;if(typeof nombre!=='string'||!nombre.trim()||nombre.length>100||typeof activo!=='boolean')fail('Nombre de 1 a 100 caracteres y estado obligatorio.');const [r]=await pool.query('UPDATE category SET category_name=?,is_active=? WHERE category_id=?',[nombre.trim(),activo?1:0,req.params.id]);if(!r.affectedRows)fail('Categoría no encontrada.',404);res.json({success:true});}));
 router.get('/config',admin,wrap(async(req,res)=>res.json(api.config)));
 router.put('/config',admin,wrap(async(req,res)=>{const ranges={upload_mb:[1,50],manual_mb:[1,100],cost_threshold:[0,100000000],saturation:[3,3]};for(const [k,[lo,hi]] of Object.entries(ranges)){if(!Number.isFinite(req.body[k])||req.body[k]<lo||req.body[k]>hi||(k!=='cost_threshold'&&!Number.isInteger(req.body[k])))fail(`${k}: valor permitido entre ${lo} y ${hi}.`);}await pool.query('UPDATE inc3_config SET upload_mb=?,manual_mb=?,cost_threshold=?,saturation=? WHERE id=1',Object.keys(ranges).map(k=>req.body[k]));api.config={...req.body};res.json({success:true});}));
 app.get('/config-public',wrap(async(req,res)=>res.json({upload_mb:api.config.upload_mb,manual_mb:api.config.manual_mb})));
 router.get('/logs',admin,wrap(async(req,res)=>res.json((await pool.query('SELECT * FROM inc3_log ORDER BY id DESC LIMIT 200'))[0])));
 router.get('/log-backup',admin,wrap(async(req,res)=>{try{const st=await fs.promises.stat(fallback);res.json({exists:true,bytes:st.size,updated_at:st.mtime});}catch(e){if(e.code!=='ENOENT')throw e;res.json({exists:false,bytes:0,updated_at:null});}}));
 router.get('/integration-activity',admin,wrap(async(req,res)=>{const [messages]=await pool.query('SELECT outcome,created_at,receipt_code,receipt_sent FROM inc3_inbox ORDER BY created_at DESC LIMIT 50');const [users]=await pool.query('SELECT first_name,operational_area,job_title,user_status FROM user WHERE directory_id IS NOT NULL ORDER BY user_id DESC LIMIT 50');res.json({messages,users});}));
 router.get('/jobs',admin,wrap(async(req,res)=>res.json((await pool.query('SELECT * FROM inc3_jobs'))[0])));
 api.availability=async()=>{const [rows]=await pool.query(`SELECT u.user_id,u.first_name,u.en_vacaciones,u.last_seen,(u.session_token IS NOT NULL AND u.last_seen>DATE_SUB(NOW(),INTERVAL 90 SECOND)) online,COUNT(t.ticket_id) carga FROM user u JOIN user_role ur ON ur.user_id=u.user_id AND ur.active=1 LEFT JOIN ticket t ON t.assigned_user_id=u.user_id AND t.status_id=1 AND t.is_archived=0 WHERE u.user_status=1 AND (ur.role_id=1 OR u.is_critical_tech=1 OR u.tipo_usuario='TECNICO') GROUP BY u.user_id`);return {updated_at:new Date().toISOString(),threshold:3,rows};};
 router.get('/availability',admin,wrap(async(req,res)=>res.json(await api.availability())));
 api.attachServer=server=>require('./availability-stream')(server,{pool,snapshot:api.availability,log:api.log});
 router.post('/heartbeat',wrap(async(req,res)=>{await pool.query('UPDATE user SET last_seen=NOW() WHERE user_id=?',[req.actor.user_id]);res.json({success:true});}));
 router.get('/competencies',admin,wrap(async(req,res)=>res.json((await pool.query('SELECT * FROM inc3_competency'))[0])));
 router.put('/competencies/:id',admin,wrap(async(req,res)=>{const ids=req.body.categories;if(!Array.isArray(ids)||ids.some(n=>!Number.isInteger(n)))fail('Categorías inválidas.');if(ids.length){const [valid]=await pool.query('SELECT category_id FROM category WHERE category_id IN (?)',[ids]);if(valid.length!==new Set(ids).size)fail('Una de las categorías seleccionadas no existe.');}const [u]=await pool.query("SELECT u.user_id FROM user u JOIN user_role ur ON ur.user_id=u.user_id WHERE u.user_id=? AND (ur.role_id=1 OR u.is_critical_tech=1 OR u.tipo_usuario='TECNICO') AND ur.active=1",[req.params.id]);if(!u.length)fail('Técnico no encontrado.',404);const c=await pool.getConnection();try{await c.beginTransaction();await c.query('DELETE FROM inc3_competency WHERE user_id=?',[req.params.id]);for(const id of new Set(ids))await c.query('INSERT INTO inc3_competency VALUES (?,?)',[req.params.id,id]);await c.query('UPDATE user SET competencies_configured=1 WHERE user_id=?',[req.params.id]);await c.commit();res.json({success:true,warning:ids.length?'':'Sin especialidades: el técnico no recibirá asignaciones automáticas.'});}finally{await c.rollback();c.release();}}));
 router.get('/archives',support,wrap(async(req,res)=>{const clauses=['t.is_archived=1'],args=[];if(req.query.q){clauses.push('(MATCH(t.title,t.description) AGAINST (? IN NATURAL LANGUAGE MODE) OR t.ticket_code LIKE ?)');args.push(req.query.q,'%'+req.query.q+'%');}for(const [key,op] of [['desde','>='],['hasta','<=']])if(req.query[key]){if(!/^\d{4}-\d{2}-\d{2}$/.test(req.query[key]))fail('Fecha inválida.');clauses.push(`DATE(t.close_date) ${op} ?`);args.push(req.query[key]);}if(req.query.category_id){clauses.push('t.category_id=?');args.push(req.query.category_id);}res.json((await pool.query('SELECT t.ticket_code,t.title,t.close_date,t.description,t.category_id FROM ticket t WHERE '+clauses.join(' AND ')+' ORDER BY t.close_date DESC LIMIT 200',args))[0]);}));
 router.get('/archives/:code',support,wrap(async(req,res)=>{const t=await ticket(req);if(!t.is_archived)fail('El ticket no está archivado.');res.json({ticket:t,comments:await obtenerComentariosParaViewer(t.ticket_id,req.actor.first_name,req.identity.obtenerPermisos().soporte)});}));
 router.get('/travel/:code',wrap(async(req,res)=>{const t=await ticket(req);res.json((await pool.query('SELECT tr.*,u.first_name FROM inc3_travel tr JOIN user u ON u.user_id=tr.user_id WHERE ticket_id=? ORDER BY id DESC',[t.ticket_id]))[0]);}));
 require('./travel')({router,admin,support,wrap,fail,pool,ticket,mutable,audit});
 // Todas las mutaciones de tickets heredadas requieren sesión e impiden editar archivados.
 app.use('/incidente',actor,wrap(async(req,res,next)=>{if(req.method!=='GET'&&req.body?.id_ticket){const t=await ticket(req);mutable(t);req.body.usuario=req.actor.first_name;if(!req.identity.obtenerPermisos().soporte&&!['/ver','/comentar','/reabrir','/cerrar'].includes(req.path))fail('Acción reservada a soporte.',403);}next();}));
 app.post('/incidente',wrap(async(req,res,next)=>{const [r]=await pool.query('SELECT * FROM category WHERE category_id=? AND is_active=1',[req.body.category_id]);if(!r.length)fail('La categoría no está disponible.');req.body.creador=req.actor.first_name;next();}));
 const transition=wrap(async(req,res)=>{const c=await pool.getConnection();let t,target;try{await c.beginTransaction();t=await ticket(req,c,true);mutable(t);const action=req.path.split('/').pop();target={ver:1,espera:2,continuar:1,cancelar:3,resolver:4,cerrar:6}[action];if(action==='ver'&&(t.status_id!==5||t.assigned_user_id!==req.actor.user_id)){if(t.requester_user_id===req.actor.user_id)await c.query('UPDATE ticket SET notify_creator=0 WHERE ticket_id=?',[t.ticket_id]);await c.commit();return res.json({cambio:false});}
 const allowed={ver:[5],espera:[1,2],continuar:[2],cancelar:[5,1,2],resolver:[1],cerrar:[4]};if(!EstadoTicket.desde(t.status_id).puedeTransitar(action))fail('Transición inválida para el estado actual.',409);
 if(action==='cerrar'&&!req.actor.admin&&t.requester_user_id!==req.actor.user_id)fail('Solo el solicitante o administrador puede cerrar.',403);
 if(action==='resolver'&&!String(req.body.info_resolucion||'').trim())fail('Describe la solución.');if(action==='espera'&&!String(req.body.info_espera||'').trim())fail('Indica el motivo de espera.');
 let sql='UPDATE ticket SET status_id=?',args=[target];if(target===2)sql+=',pausa_inicio=COALESCE(pausa_inicio,NOW())';if(action==='continuar')sql+=',sla_deadline=DATE_ADD(sla_deadline,INTERVAL COALESCE(TIMESTAMPDIFF(SECOND,pausa_inicio,NOW()),0) SECOND),sla_paused_seconds=sla_paused_seconds+COALESCE(TIMESTAMPDIFF(SECOND,pausa_inicio,NOW()),0),pausa_inicio=NULL';if(target===4)sql+=',resolution_date=NOW(),survey_version=(SELECT MAX(id) FROM inc3_survey_version)';if(target===6)sql+=',close_date=NOW(),auto_cerrado=1,survey_version=IF(EXISTS(SELECT 1 FROM inc3_survey_answer WHERE ticket_id=ticket.ticket_id),survey_version,(SELECT MAX(id) FROM inc3_survey_version))';sql+=',notify_creator=1 WHERE ticket_id=?';args.push(t.ticket_id);await c.query(sql,args);
 const names={1:'En curso',2:'En espera',3:'Cancelado',4:'Resuelto',5:'Pendiente',6:'Cerrado'};
 await c.query('INSERT INTO comment(content,user_id,ticket_id) VALUES (?,?,?)',[`Cambio de estado: ${names[t.status_id]} → ${names[target]}. ${req.body.info_resolucion||req.body.info_espera||req.body.info_cancelar||''}`,req.actor.user_id,t.ticket_id]);await audit(c,req,t,'CAMBIO_ESTADO',names[t.status_id],names[target]);await c.commit();
 }finally{await c.rollback();c.release();}
 if(target===4){const [[creator]]=await pool.query('SELECT first_name,institutional_email FROM user WHERE user_id=?',[t.requester_user_id]);enviarEmailTicketResuelto(creator.institutional_email,{ticketCode:t.ticket_code,creador:creator.first_name,aparato:t.title,descripcion:t.description,fechaCreacion:t.creation_date,fechaResolucion:new Date().toLocaleString('es-CL'),tecnico:req.actor.first_name,resolucion:req.body.info_resolucion});}
 res.json({success:true,cambio:true,nuevoEstado:{1:'En curso',2:'En espera',3:'Cancelado',4:'Resuelto',6:'Cerrado'}[target],comentarios:await obtenerComentariosParaViewer(t.ticket_id,req.actor.first_name,req.identity.obtenerPermisos().soporte)});
 });for(const name of ['ver','espera','continuar','cancelar','resolver','cerrar'])app.post('/incidente/'+name,transition);
 router.get('/surveys',admin,wrap(async(req,res)=>res.json((await pool.query('SELECT * FROM inc3_survey_version ORDER BY id DESC'))[0])));
 router.post('/surveys',admin,wrap(async(req,res)=>{const q=req.body.questions;if(!Array.isArray(q)||!q.length||q.length>10||q.some(s=>typeof s!=='string'||!s.trim()||s.length>200||/[<>\x00-\x1f]/.test(s)))fail('Usa entre 1 y 10 preguntas de hasta 200 caracteres, sin HTML ni caracteres de control.');const [r]=await pool.query('INSERT INTO inc3_survey_version(questions) VALUES (?)',[JSON.stringify(q)]);res.json({success:true,id:r.insertId});}));
 router.get('/survey/:code',wrap(async(req,res)=>{const t=await ticket(req);if(![4,6].includes(t.status_id))fail('El ticket debe estar resuelto.');const [[v]]=await pool.query('SELECT * FROM inc3_survey_version WHERE id=COALESCE(?,(SELECT MIN(id) FROM inc3_survey_version))',[t.survey_version]);res.json({...v,answered:(await pool.query('SELECT 1 FROM inc3_survey_answer WHERE ticket_id=?',[t.ticket_id]))[0].length>0});}));
 router.post('/survey/:code',wrap(async(req,res)=>{const t=await ticket(req);mutable(t);if(t.requester_user_id!==req.actor.user_id||![4,6].includes(t.status_id))fail('Solo el solicitante puede responder tras la resolución.',403);const [[v]]=await pool.query('SELECT * FROM inc3_survey_version WHERE id=COALESCE(?,(SELECT MIN(id) FROM inc3_survey_version))',[t.survey_version]);const questions=typeof v.questions==='string'?JSON.parse(v.questions):v.questions;const a=req.body.answers;if(!Array.isArray(a)||a.length!==questions.length||a.some(n=>!Number.isInteger(n)||n<1||n>5))fail('Responde cada pregunta de 1 a 5.');await pool.query('INSERT INTO inc3_survey_answer(ticket_id,version_id,user_id,answers) VALUES (?,?,?,?)',[t.ticket_id,v.id,req.actor.user_id,JSON.stringify(a)]);res.json({success:true});}));
 router.get('/survey-results',admin,wrap(async(req,res)=>res.json((await pool.query('SELECT a.*,t.ticket_code,v.questions FROM inc3_survey_answer a JOIN ticket t ON t.ticket_id=a.ticket_id JOIN inc3_survey_version v ON v.id=a.version_id ORDER BY a.created_at DESC LIMIT 200'))[0])));
 router.get('/attachments/:code',wrap(async(req,res)=>{const t=await ticket(req);res.json((await pool.query('SELECT attachment_id,file_name,is_deleted,deleted_at,purged_at FROM attachment WHERE ticket_id=?',[t.ticket_id]))[0]);}));
 router.get('/trash',admin,wrap(async(req,res)=>res.json((await pool.query('SELECT a.attachment_id,a.file_name,a.deleted_at,a.purged_at,t.ticket_code FROM attachment a JOIN ticket t ON t.ticket_id=a.ticket_id WHERE a.is_deleted=1 ORDER BY a.deleted_at DESC LIMIT 200'))[0])));
 router.post('/attachments/:id/:action',admin,wrap(async(req,res)=>{const c=await pool.getConnection();try{await c.beginTransaction();const [[a]]=await c.query('SELECT a.*,t.is_archived FROM attachment a JOIN ticket t ON t.ticket_id=a.ticket_id WHERE attachment_id=? FOR UPDATE',[req.params.id]);if(!a)fail('Adjunto no encontrado.',404);mutable(a);if(req.params.action==='restore'){if(a.purged_at||!a.deleted_at||Date.now()-new Date(a.deleted_at)>48*3600000||!fs.existsSync(path.join(uploadDir,path.basename(a.file_path))))fail('La evidencia expiró o ya no existe físicamente.',410);await c.query('UPDATE attachment SET is_deleted=0,deleted_at=NULL WHERE attachment_id=?',[a.attachment_id]);}else if(req.params.action==='delete'){await c.query('UPDATE attachment SET is_deleted=1,deleted_at=COALESCE(deleted_at,NOW()) WHERE attachment_id=?',[a.attachment_id]);}else fail('Acción inválida.');await c.commit();res.json({success:true});}finally{await c.rollback();c.release();}}));
 const excel=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1}}).single('archivo');
 router.get('/users/template',admin,(req,res)=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['nombre','rut','correo','password','area','piso','cargo']]),'Usuarios');res.attachment('plantilla-usuarios.xlsx').send(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}));});
 router.post('/users/import',admin,(req,res)=>excel(req,res,e=>{if(e)return res.status(400).json({error:'Excel máximo 5 MB.'});wrap(async(req,res)=>{
 if(!req.file||!req.file.originalname.toLowerCase().endsWith('.xlsx'))fail('Selecciona un archivo .xlsx.');let rows;try{const w=XLSX.read(req.file.buffer,{type:'buffer',raw:true});rows=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:''});}catch{fail('Excel inválido.');}if(!rows.length||rows.length>1000)fail('Entre 1 y 1000 filas.');const errors=[];let imported=0;
 for(let i=0;i<rows.length;i++){const row=rows[i];let c;try{const rut=String(row.rut||'').replaceAll('.','').toUpperCase();if(!validarRutModulo11(rut))fail('RUT inválido.');if(!row.nombre||String(row.nombre).length>50||!/^\S+@\S+\.\S+$/.test(row.correo)||String(row.correo).length>150||(row.password==null||String(row.password).length<8)||Buffer.byteLength(String(row.password),'utf8')>72)fail('Nombre, correo o contraseña temporal inválidos.');if(String(row.area).length>100||String(row.piso).length>50||String(row.cargo).length>100)fail('Área, piso o cargo demasiado largo.');const hash=await passwords.hash(String(row.password));c=await pool.getConnection();await c.beginTransaction();const [r]=await c.query("INSERT INTO user(first_name,first_last_name,second_last_name,institutional_email,rut,username,password_hash,operational_area,operational_floor,job_title,must_reset_password) VALUES (?,'','',?,?,?,?,?,?,?,1)",[row.nombre,row.correo,rut,rut,hash,row.area||'',row.piso||'',row.cargo||'']);await c.query('INSERT INTO user_role(assignment_date,active,role_id,user_id) VALUES(NOW(),1,2,?)',[r.insertId]);await c.commit();imported++;}catch(error){errors.push({fila:i+2,error:error.code==='ER_DUP_ENTRY'?'RUT o correo duplicado.':error.status?error.message:'No se pudo importar la fila.'});}finally{if(c){await c.rollback();c.release();}}}
 res.json({success:true,importados:imported,fallidos:errors.length,errores:errors});})(req,res);}));
 require('./increment3-jobs')(api,{pool,router,admin,wrap,fail,uploadDir,transporter,validarRutModulo11,passwords});
 router.get('/alerts',admin,wrap(async(req,res)=>res.json((await pool.query("SELECT COUNT(*) total FROM inc3_log WHERE severity='critical' AND created_at>DATE_SUB(NOW(),INTERVAL 24 HOUR)"))[0][0])));
 // Se aplica a las comunicaciones existentes, sin cambiar sus destinatarios ni el contenido de negocio.
 const originalMail=transporter.sendMail.bind(transporter);
 transporter.sendMail=(options,callback)=>{const promise=(async()=>{await api.ready;const html=options.html&&!options.clinicTemplateApplied?await api.render('email',{nombre_ticket:(options.subject||'').match(/INC\d+/)?.[0]||options.subject,usuario:'',contenido:options.html}):undefined;const {clinicTemplateApplied,...mailOptions}=options;return new NotificacionCorreo(originalMail).enviar({...mailOptions,...(html?{html}:{} )});})();if(callback){promise.then(r=>callback(null,r),e=>callback(e));return;}return promise;};
 app.use('/uploads',wrap(async(req,res,next)=>{const filename=path.basename(decodeURIComponent(req.path));const [r]=await pool.query('SELECT is_deleted FROM attachment WHERE file_path=?',['/uploads/'+filename]);if(r.some(a=>a.is_deleted))return res.status(410).send('Evidencia en papelera o purgada.');next();}));
 api.captureErrors=()=>{
  const originalError=console.error.bind(console);console.error=(...args)=>{originalError(...args);api.log(args.find(x=>x instanceof Error)||new Error(args.map(String).join(' ')),'error',{source:'backend'}).catch(()=>{});};
  process.on('uncaughtExceptionMonitor',error=>{fs.mkdirSync(path.dirname(fallback),{recursive:true});fs.appendFileSync(fallback,JSON.stringify({date:new Date().toISOString(),severity:'critical',message:redact(error.message),stack:redact(error.stack)})+'\n');});
  app.use((err,req,res,next)=>{api.log(err,'critical',{path:req.path});if(!res.headersSent)res.status(500).json({error:'Error interno registrado. Contacta al administrador.'});else next(err);});
 };
 return api;
};
